"""create_initial_tables.

Revision ID: 9349c3b866c3
Revises:
Create Date: 2026-01-10 13:07:55.764976

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9349c3b866c3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "keywords",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("term", sa.String(length=100), nullable=False),
        sa.Column("keyword_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keywords_user_id"), "keywords", ["user_id"], unique=False)
    op.create_table(
        "monitored_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("linkedin_url", sa.String(length=500), nullable=False),
        sa.Column("profile_type", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "crawl_frequency_hours", sa.Integer(), server_default=sa.text("24"), nullable=False
        ),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitored_profiles_user_id"), "monitored_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "linkedin_posts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("keyword_id", sa.UUID(), nullable=True),
        sa.Column("linkedin_post_id", sa.String(length=100), nullable=False),
        sa.Column("author_name", sa.String(length=200), nullable=False),
        sa.Column("author_linkedin_url", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["profile_id"], ["monitored_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_posts_keyword_id"), "linkedin_posts", ["keyword_id"], unique=False
    )
    op.create_index(
        op.f("ix_linkedin_posts_linkedin_post_id"),
        "linkedin_posts",
        ["linkedin_post_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_linkedin_posts_profile_id"), "linkedin_posts", ["profile_id"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("event_timing", sa.String(length=20), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column(
            "event_date_inferred", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("companies_mentioned", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("people_mentioned", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("raw_llm_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["linkedin_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_post_id"), "signals", ["post_id"], unique=False)
    op.create_index(op.f("ix_signals_user_id"), "signals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_user_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_post_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_linkedin_posts_profile_id"), table_name="linkedin_posts")
    op.drop_index(op.f("ix_linkedin_posts_linkedin_post_id"), table_name="linkedin_posts")
    op.drop_index(op.f("ix_linkedin_posts_keyword_id"), table_name="linkedin_posts")
    op.drop_table("linkedin_posts")
    op.drop_index(op.f("ix_monitored_profiles_user_id"), table_name="monitored_profiles")
    op.drop_table("monitored_profiles")
    op.drop_index(op.f("ix_keywords_user_id"), table_name="keywords")
    op.drop_table("keywords")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
