"""add_linkedin_models_with_enums.

Revision ID: a89a422dd59b
Revises:
Create Date: 2026-01-10 13:31:29.735211

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a89a422dd59b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "linkedin_monitored_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column(
            "profile_type",
            postgresql.ENUM("company", "personal", name="profile_type"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "crawl_frequency_hours", sa.Integer(), server_default=sa.text("24"), nullable=False
        ),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_monitored_profiles_user_id"),
        "linkedin_monitored_profiles",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "linkedin_searches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("term", sa.String(length=100), nullable=False),
        sa.Column(
            "search_type", postgresql.ENUM("keyword", "hashtag", name="search_type"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_searches_user_id"), "linkedin_searches", ["user_id"], unique=False
    )
    op.create_table(
        "linkedin_posts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("search_id", sa.UUID(), nullable=True),
        sa.Column("linkedin_post_id", sa.String(length=100), nullable=False),
        sa.Column("author_name", sa.String(length=200), nullable=False),
        sa.Column("author_linkedin_url", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["linkedin_monitored_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["search_id"], ["linkedin_searches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_posts_linkedin_post_id"),
        "linkedin_posts",
        ["linkedin_post_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_linkedin_posts_profile_id"), "linkedin_posts", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_linkedin_posts_search_id"), "linkedin_posts", ["search_id"], unique=False
    )
    op.create_table(
        "linkedin_signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column(
            "event_timing",
            postgresql.ENUM("past", "future", "unknown", name="event_timing"),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column(
            "event_date_inferred", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("companies_mentioned", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("people_mentioned", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("raw_llm_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["linkedin_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_signals_post_id"), "linkedin_signals", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_linkedin_signals_user_id"), "linkedin_signals", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_linkedin_signals_user_id"), table_name="linkedin_signals")
    op.drop_index(op.f("ix_linkedin_signals_post_id"), table_name="linkedin_signals")
    op.drop_table("linkedin_signals")
    op.drop_index(op.f("ix_linkedin_posts_search_id"), table_name="linkedin_posts")
    op.drop_index(op.f("ix_linkedin_posts_profile_id"), table_name="linkedin_posts")
    op.drop_index(op.f("ix_linkedin_posts_linkedin_post_id"), table_name="linkedin_posts")
    op.drop_table("linkedin_posts")
    op.drop_index(op.f("ix_linkedin_searches_user_id"), table_name="linkedin_searches")
    op.drop_table("linkedin_searches")
    op.drop_index(
        op.f("ix_linkedin_monitored_profiles_user_id"), table_name="linkedin_monitored_profiles"
    )
    op.drop_table("linkedin_monitored_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
